version: '2'
services:
  restmongoservice:
    image: rest-monog-service
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
